CREATE DATABASE IF NOT EXISTS byungdduggung;
USE byungdduggung;

CREATE TABLE IF NOT EXISTS score (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL,
    department VARCHAR(255) NOT NULL,
    similarity DOUBLE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);